version: 2
updates:
  # Python dependencies for cezzis-kafka
  - package-ecosystem: "pip"
    directory: "/kafka-packages"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "mtnvencenzo"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Python dependencies for cezzis-otel
  - package-ecosystem: "pip"
    directory: "/otel-packages"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "mtnvencenzo"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    assignees:
      - "mtnvencenzo"
    commit-message:
      prefix: "chore"
      include: "scope"